openapi: 3.0.0
info:
  title: RedStone MCP Template
  description: A Model Context Protocol (MCP) server that provides data feeds from RedStone Oracle
  version: 0.0.1
servers:
  - url: http://localhost:3001
    description: Local development server
paths:
  /mcp:
    get:
      summary: Get the MCP server status
      tags:
        - MCP
      responses:
        '200':
          description: Successful response with MCP server status
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                  id:
                    type: integer
                    example: -1
                  result:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "redstone-mcp running. See `/llms.txt` for machine-readable docs."
    post:
      summary: Send a JSON-RPC message to the MCP server
      tags:
        - MCP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JSONRPCRequest'
      responses:
        '200':
          description: Successful response with JSON-RPC result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONRPCResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete a session from the MCP server
      tags:
        - MCP
      responses:
        '200':
          description: Successful session deletion response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONRPCResponse'
  /:
    get:
      summary: Root endpoint to check server status
      tags:
        - Status
      responses:
        '200':
          description: Server status message
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                  id:
                    type: integer
                    example: -1
                  result:
                    type: object
                    properties:
                      message:
                        type: string
components:
  schemas:
    JSONRPCRequest:
      type: object
      properties:
        jsonrpc:
          type: string
          description: JSON-RPC version
          example: "2.0"
        id:
          oneOf:
            - type: string
            - type: integer
            - type: "null"
          description: Request identifier
        method:
          type: string
          description: Method to call
          example: "call_tool"
        params:
          type: object
          description: Method parameters
      required:
        - jsonrpc
        - method
    JSONRPCResponse:
      type: object
      properties:
        jsonrpc:
          type: string
          description: JSON-RPC version
          example: "2.0"
        id:
          oneOf:
            - type: string
            - type: integer
            - type: "null"
          description: Request identifier
        result:
          type: object
          description: Result object
      required:
        - jsonrpc
        - id
    JSONRPCError:
      type: object
      properties:
        jsonrpc:
          type: string
          description: JSON-RPC version
          example: "2.0"
        id:
          oneOf:
            - type: string
            - type: integer
            - type: "null"
          description: Request identifier
        error:
          type: object
          properties:
            code:
              type: integer
              description: Error code
            message:
              type: string
              description: Error message
            data:
              type: object
              description: Additional error data
      required:
        - jsonrpc
        - id
        - error
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
      required:
        - error
    TradeInfo:
      type: object
      properties:
        bidPrice:
          type: number
          format: double
          description: Current bid price
          example: 253.12
        askPrice:
          type: number
          format: double
          description: Current ask price
          example: 253.18
        volumeInUsd:
          type: number
          format: double
          description: Trading volume in USD
          example: 4533158.148519999
      required:
        - volumeInUsd

    SlippageInfo:
        type: object
        properties:
          isSuccess:
            type: boolean
            description: Whether the slippage simulation was successful
            example: true
          slippageAsPercent:
            type: string
            description: Slippage percentage as string
            example: "0.005309"
          direction:
            type: string
            enum: [ buy, sell ]
            description: Trade direction for slippage calculation
            example: "buy"
          simulationValueInUsd:
            type: string
            description: USD value used for slippage simulation
            example: "20000"
        required:
          - isSuccess
          - slippageAsPercent
          - direction
          - simulationValueInUsd

    SourcePriceInfo:
        type: object
        properties:
          sourceName:
            type: string
            description: Name of the price source (exchange or data provider)
            example: "binance-usdt"
          price:
            type: number
            format: double
            description: Price from this source
            example: 253.10361369999998
          tradeInfo:
            $ref: '#/components/schemas/TradeInfo'
          slippage:
            type: array
            items:
              $ref: '#/components/schemas/SlippageInfo'
            description: Slippage information for DEX sources
        required:
          - sourceName
          - price

    TokenPriceData:
        type: object
        properties:
          dataFeedId:
            type: string
            description: Token or data feed identifier
            example: "AAVE"
          finalPrice:
            type: number
            format: double
            description: Final aggregated price from the oracle
            example: 252.985
          timestamp:
            type: integer
            format: int64
            description: Timestamp in milliseconds
            example: 1749397130000
          nodeLabel:
            type: string
            description: Oracle node label that provided this data
            example: "morpheus-main"
          signerAddress:
            type: string
            pattern: "^0x[a-fA-F0-9]{40}$"
            description: Ethereum address of the data signer
            example: "0x51Ce04Be4b3E32572C4Ec9135221d0691Ba7d202"
          sources:
            type: array
            items:
              $ref: '#/components/schemas/SourcePriceInfo'
            description: Individual price sources with their data
        required:
          - dataFeedId
          - finalPrice
          - timestamp
          - nodeLabel
          - signerAddress
          - sources

    MappedRedStoneData:
        type: object
        additionalProperties:
          $ref: '#/components/schemas/TokenPriceData'
        description: Mapped RedStone data keyed by data feed ID
        example:
          AAVE:
            dataFeedId: "AAVE"
            finalPrice: 252.985
            timestamp: 1749397130000
            nodeLabel: "morpheus-main"
            signerAddress: "0x51Ce04Be4b3E32572C4Ec9135221d0691Ba7d202"
            sources:
              - sourceName: "binance-usdt"
                price: 253.10361369999998
                tradeInfo:
                  bidPrice: 253.10361369999998
                  askPrice: 253.1136174
                  volumeInUsd: 15661544.60705
